const DESKTOP_DISPLAY = 1279;
const TABLET_DISPLAY = 768;
const DESKTOP_CARDS = 12;
const TABLET_CARDS = 8;
const MOBILE_CARDS = 5;
const DESKTOP_MORE = 3;
const TABLET_MORE = 2;
const MOBILE_MORE = 1;

export {
  DESKTOP_DISPLAY,
  TABLET_DISPLAY,
  DESKTOP_CARDS,
  TABLET_CARDS,
  MOBILE_CARDS,
  DESKTOP_MORE,
  TABLET_MORE,
  MOBILE_MORE,
};
